#!/usr/bin/env bash
# Bring up a real Headscale control plane and three real Tailscale clients on
# this machine, with no Docker, no root and no TUN device.
#
#   ./lab/up.sh            start the server, enrol three nodes, verify
#   ./lab/down.sh          stop everything this script started
#
# Everything lives under lab/.run/ (git ignored): binaries, database, keys,
# sockets, logs, exports.
set -euo pipefail

LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_DIR="$LAB_DIR/.run"
BIN_DIR="$RUN_DIR/bin"
LOG_DIR="$RUN_DIR/logs"

# Pinned versions. Both are the stable releases the audit targets.
HEADSCALE_VERSION="${HEADSCALE_VERSION:-0.29.3}"
TAILSCALE_VERSION="${TAILSCALE_VERSION:-1.102.3}"

# Ports chosen away from the defaults so the lab cannot collide with a real
# headscale or tailscaled on the same machine.
HS_PORT="${HS_PORT:-18080}"
HS_METRICS_PORT="${HS_METRICS_PORT:-19090}"
HS_GRPC_PORT="${HS_GRPC_PORT:-15043}"
SERVER_URL="http://127.0.0.1:${HS_PORT}"

say() { printf '\n== %s\n' "$*"; }
die() { printf 'lab: %s\n' "$*" >&2; exit 1; }

hs()  { "$BIN_DIR/headscale" -c "$RUN_DIR/config.yaml" "$@"; }

wait_for() { # wait_for <seconds> <description> <command...>
  local deadline=$(( $(date +%s) + $1 )); local what="$2"; shift 2
  until "$@" >/dev/null 2>&1; do
    [ "$(date +%s)" -lt "$deadline" ] || die "timed out waiting for $what"
    sleep 0.3
  done
}

fetch_headscale() {
  [ -x "$BIN_DIR/headscale" ] && return 0
  local os arch url
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  case "$(uname -m)" in
    arm64|aarch64) arch=arm64 ;;
    x86_64|amd64)  arch=amd64 ;;
    *) die "unsupported architecture $(uname -m)" ;;
  esac
  url="https://github.com/juanfont/headscale/releases/download/v${HEADSCALE_VERSION}/headscale_${HEADSCALE_VERSION}_${os}_${arch}"
  say "downloading headscale ${HEADSCALE_VERSION} (${os}/${arch})"
  curl -fsSL -o "$BIN_DIR/headscale" "$url"
  chmod +x "$BIN_DIR/headscale"
  curl -fsSL -o "$RUN_DIR/checksums.txt" \
    "https://github.com/juanfont/headscale/releases/download/v${HEADSCALE_VERSION}/checksums.txt" || true
  if [ -s "$RUN_DIR/checksums.txt" ] && command -v shasum >/dev/null; then
    local want got
    want="$(grep " headscale_${HEADSCALE_VERSION}_${os}_${arch}\$" "$RUN_DIR/checksums.txt" | awk '{print $1}')"
    got="$(shasum -a 256 "$BIN_DIR/headscale" | awk '{print $1}')"
    [ -z "$want" ] || [ "$want" = "$got" ] || die "headscale checksum mismatch"
    printf 'headscale checksum verified: %s\n' "$got"
  fi
}

fetch_tailscale() {
  [ -x "$BIN_DIR/tailscaled" ] && [ -x "$BIN_DIR/tailscale" ] && return 0
  local os arch
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  case "$(uname -m)" in
    arm64|aarch64) arch=arm64 ;;
    x86_64|amd64)  arch=amd64 ;;
    *) die "unsupported architecture $(uname -m)" ;;
  esac
  if [ "$os" = "linux" ]; then
    say "downloading tailscale ${TAILSCALE_VERSION} (static ${arch})"
    curl -fsSL "https://pkgs.tailscale.com/stable/tailscale_${TAILSCALE_VERSION}_${arch}.tgz" \
      | tar -xz -C "$RUN_DIR"
    mv "$RUN_DIR/tailscale_${TAILSCALE_VERSION}_${arch}/tailscale" "$BIN_DIR/"
    mv "$RUN_DIR/tailscale_${TAILSCALE_VERSION}_${arch}/tailscaled" "$BIN_DIR/"
    rm -rf "$RUN_DIR/tailscale_${TAILSCALE_VERSION}_${arch}"
    return 0
  fi
  # macOS: Tailscale ships an app bundle, not a standalone daemon, so the lab
  # builds the two commands from the pinned upstream module instead.
  command -v go >/dev/null || die \
    "no tailscaled: install Go (brew install go) so the lab can build tailscale ${TAILSCALE_VERSION} from source"
  say "building tailscale ${TAILSCALE_VERSION} from source (a few minutes, once)"
  GOBIN="$BIN_DIR" go install "tailscale.com/cmd/tailscaled@v${TAILSCALE_VERSION}"
  GOBIN="$BIN_DIR" go install "tailscale.com/cmd/tailscale@v${TAILSCALE_VERSION}"
}

write_config() {
  cat > "$RUN_DIR/config.yaml" <<EOF
# Generated by lab/up.sh. A loopback laboratory, not a production template:
# server_url is plain http because a local lab cannot hold a public
# certificate, and the audit reports that honestly.
server_url: ${SERVER_URL}
listen_addr: 127.0.0.1:${HS_PORT}
metrics_listen_addr: 127.0.0.1:${HS_METRICS_PORT}
grpc_listen_addr: 127.0.0.1:${HS_GRPC_PORT}
grpc_allow_insecure: false
trusted_proxies: []

noise:
  private_key_path: ${RUN_DIR}/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

derp:
  server:
    enabled: false
  urls: []
  # Headscale refuses to start with an empty DERP map; this local file keeps
  # the lab from calling Tailscale's public relays.
  paths:
    - ${RUN_DIR}/derp.yaml
  auto_update_enabled: false
  update_frequency: 24h

disable_check_updates: true

node:
  expiry: 180d
  ephemeral:
    inactivity_timeout: 5m

database:
  type: sqlite
  sqlite:
    path: ${RUN_DIR}/db.sqlite
    write_ahead_log: true

log:
  level: info
  format: text

policy:
  mode: file
  path: ${RUN_DIR}/policy.hujson

dns:
  magic_dns: true
  base_domain: lab.internal
  override_local_dns: false
  nameservers:
    global: []
    split: {}
  search_domains: []
  extra_records: []

unix_socket: ${RUN_DIR}/headscale.sock
unix_socket_permission: "0770"

logtail:
  enabled: false

taildrop:
  enabled: false
EOF
  cp "$LAB_DIR/policy.lab.openall.hujson" "$RUN_DIR/policy.hujson"
  cp "$LAB_DIR/derp.lab.yaml" "$RUN_DIR/derp.yaml"
}

start_server() {
  say "starting headscale ${HEADSCALE_VERSION} on ${SERVER_URL}"
  ( "$BIN_DIR/headscale" -c "$RUN_DIR/config.yaml" serve >"$LOG_DIR/headscale.log" 2>&1 &
    echo $! > "$RUN_DIR/headscale.pid" )
  wait_for 45 "the headscale API" \
    curl -fsS "${SERVER_URL}/health"
  hs users list >/dev/null || die "headscale is up but the CLI cannot reach it"
}

main() {
  mkdir -p "$BIN_DIR" "$LOG_DIR"
  if [ -f "$RUN_DIR/headscale.pid" ] && kill -0 "$(cat "$RUN_DIR/headscale.pid")" 2>/dev/null; then
    die "the lab is already running (see lab/.run/headscale.pid); run ./lab/down.sh first"
  fi
  fetch_headscale
  fetch_tailscale
  "$BIN_DIR/headscale" version
  "$BIN_DIR/tailscale" version | head -1
  write_config
  start_server
  "$LAB_DIR/enroll_local.sh"
  "$LAB_DIR/verify.sh"
  say "lab is up. Audit it with:"
  printf '  ./lab/audit.sh\n'
}

main "$@"
